GET http://localhost:3000/api/events HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3000/api/events HTTP/1.1
Content-Type: application/json

{
"events":{
  "eventName": "Kurushetra",
  "description": "A symposium on the latest tech trends and innovations.",
  "rollNo": "2022103012",
  "contact": "48611481",
  "organizerName": "Hariguru",
  "domain": "Tech-ops",
  "date": "2024-11-10",
  "startTime": "10:00",
  "endTime": "14:00"
},
"list":[
    {
        "product":"pen",
        "count":10,
        "category":"c1"
    },
    {
        "product":"pencil",
        "count":10,
        "category":"c1"
    }

]
}
###
POST http://localhost:3000/api/lists HTTP/1.1
Content-Type: application/json

{
"items":
[{
    "eventId":1,
    "itemName":"book",
    "count":11,
    "approvedCount":0,
    "category":"c1"
},
{
    "eventId":1,
    "itemName":"charger",
    "count":5,
    "approvedCount":0,
    "category":"c1"
}
],
"eventName":"vyuha",
"domain":"events"
}